### ISSUE TITLE
ENHANCEMENT validation configuration

### ISSUE THREAD

**Issue by muskie9** [dynamic/silverstripe-flexslider#152]
**Summary**

We've found some instances where `SlideImage` is extended for an instance not needing the image, or allowing for additional options. Currently the validation is strict in requiring the `SlideImage` record.

**Proposed Solution**

Additional logic in the `SlideImage::validate()` method to allow for customization of the required `ImageID` field.

_config.yml
```yml
Dynamic\FlexSlider\Model\SlideImage
  require_image: false

# MyPage extends \Page
Foo\Bar\MyPage:
  extensions:
    - Dynamic\FlexSlider\ORM\FlexSlider
  require_image: true
```

Validation should check if the related object has a config override for `require_image`. If no config is found, it should fall back to the `SlideImage`'s config for `require_image`. This allows for a global setting (default of `true`) as well as model specific overrides.
